//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernateClassGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHibernateClassGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;.
        /// </summary>
        internal static string Enity_Using {
            get {
                return ResourceManager.GetString("Enity_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class {0} {1}.
        /// </summary>
        internal static string Entity_Class {
            get {
                return ResourceManager.GetString("Entity_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace {0}.
        /// </summary>
        internal static string Entity_Namespace {
            get {
                return ResourceManager.GetString("Entity_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public virtual {0} {1}.
        /// </summary>
        internal static string Entity_Propertie {
            get {
                return ResourceManager.GetString("Entity_Propertie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class {0} : ClassMap&lt;{1}&gt;.
        /// </summary>
        internal static string Map_Class {
            get {
                return ResourceManager.GetString("Map_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map(x =&gt; x.{0}, &quot;{1}&quot;);.
        /// </summary>
        internal static string Map_Column {
            get {
                return ResourceManager.GetString("Map_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public {0}().
        /// </summary>
        internal static string Map_Constructor {
            get {
                return ResourceManager.GetString("Map_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id(x =&gt; x.{0}, &quot;{1}&quot;).
        /// </summary>
        internal static string Map_Id {
            get {
                return ResourceManager.GetString("Map_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .KeyProperty(x =&gt; x.{0}, &quot;{1}&quot;).
        /// </summary>
        internal static string Map_KeyProperty {
            get {
                return ResourceManager.GetString("Map_KeyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .KeyReference(x =&gt; x.{0}, &quot;{1}&quot;).
        /// </summary>
        internal static string Map_KeyReference {
            get {
                return ResourceManager.GetString("Map_KeyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace {0}.
        /// </summary>
        internal static string Map_Namespace {
            get {
                return ResourceManager.GetString("Map_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map(x =&gt; x.{0}, &quot;{1}&quot;).
        /// </summary>
        internal static string Map_Prop_Column {
            get {
                return ResourceManager.GetString("Map_Prop_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table(&quot;{0}&quot;);.
        /// </summary>
        internal static string Map_Table {
            get {
                return ResourceManager.GetString("Map_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using FluentNHibernate.Mapping;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;.
        /// </summary>
        internal static string Map_Using {
            get {
                return ResourceManager.GetString("Map_Using", resourceCulture);
            }
        }
    }
}
